//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string MoblieNumber { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    }
}
